GROUNDWORK-2421: convert all octets metrics to bytes
gwos/tcg pull request #312
Opened 2023-06-01 15:15 UTC by VladislavSenkevich

+ add additional in/out per second metrics

2023-06-02 11:29 UTC, ymkins requested changes

2023-06-02 11:29 UTC, ymkins commented on connectors/snmp-connector/snmpConnectorModel.go
> +		bytesInPrev, bytesOutPrev, bytesInX64Prev, bytesOutX64Prev := -1, -1, -1, -1
these vars should be defined as int64

2023-06-02 11:29 UTC, ymkins commented on connectors/snmp-connector/snmpConnectorModel.go
> +			bytesInX64Prev = val.(int)
should be val.(int64) there

2023-06-02 11:29 UTC, ymkins commented on connectors/snmp-connector/snmpConnectorModel.go
> +			bytesOutX64Prev = val.(int)
should be val.(int64) there

2023-06-02 11:29 UTC, ymkins commented on connectors/snmp-connector/snmpConnectorModel.go
> +	Value int
should be defined as int64

2023-06-02 11:29 UTC, ymkins commented on connectors/snmp-connector/snmpConnectorModel.go
> +	previousX64 int, timestamp *transit.Timestamp) connectors.MetricBuilder {
should be int64 there

2023-06-05 15:13 UTC, VladislavSenkevich commented on connectors/snmp-connector/snmpConnectorModel.go
> +		bytesInPrev, bytesOutPrev, bytesInX64Prev, bytesOutX64Prev := -1, -1, -1, -1
Done

2023-06-05 15:13 UTC, VladislavSenkevich commented on connectors/snmp-connector/snmpConnectorModel.go
> +			bytesOutX64Prev = val.(int)
Done

2023-06-05 15:13 UTC, VladislavSenkevich commented on connectors/snmp-connector/snmpConnectorModel.go
> +	Value int
Done

2023-06-05 15:13 UTC, VladislavSenkevich commented on connectors/snmp-connector/snmpConnectorModel.go
> +	previousX64 int, timestamp *transit.Timestamp) connectors.MetricBuilder {
Done

2023-06-05 16:10 UTC, ymkins approved these changes

2023-07-06 06:32 UTC, merged